# Generated by Django 4.0 on 2022-05-08 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_rename_name_dog_shelterluv_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='shelterluv_status',
            field=models.CharField(default='Available for Adoption', max_length=200),
        ),
    ]
