# Generated by Django 4.0 on 2022-07-29 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0003_dog_shelterluv_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
