# Generated by Django 4.1 on 2022-12-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0003_dog_shelterluv_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='name',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
