# Generated by Django 4.0 on 2022-07-30 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0004_dog_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='offsite',
            field=models.BooleanField(default=False),
        ),
    ]
