# Generated by Django 4.1 on 2022-12-24 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0004_dog_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('shelterluv_id', models.CharField(default='', max_length=200)),
                ('shelterluv_status', models.CharField(default='Available for Adoption', max_length=200)),
                ('info', models.JSONField()),
                ('offsite', models.BooleanField(default=False)),
                ('appt_only', models.BooleanField(default=False)),
                ('host_date', models.DateField(blank=True, default=datetime.date(2000, 1, 1))),
                ('foster_date', models.DateField(blank=True, default=datetime.date(2000, 1, 1))),
            ],
            options={
                'ordering': ('name', 'id'),
            },
        ),
    ]
