# Generated by Django 4.1 on 2023-01-07 05:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0005_dogprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogprofile',
            name='update_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2000, 1, 1, 0, 0)),
        ),
    ]
