# Generated by Django 4.0 on 2022-07-31 21:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0005_dog_offsite'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='foster_date',
            field=models.DateField(blank=True, default=datetime.date(2000, 1, 1)),
        ),
        migrations.AddField(
            model_name='dog',
            name='host_date',
            field=models.DateField(blank=True, default=datetime.date(2000, 1, 1)),
        ),
    ]
