# Generated by Django 4.1 on 2023-01-07 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopter', '0063_alter_adopter_accept_date_alter_adopter_alert_date_and_more'),
        ('wishlist', '0007_dogprofile_litter_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('shelterluv_id', models.CharField(default='', max_length=200)),
                ('shelterluv_status', models.CharField(default='Available for Adoption', max_length=200)),
                ('info', models.JSONField()),
                ('offsite', models.BooleanField(default=False)),
                ('appt_only', models.BooleanField(default=False)),
                ('host_date', models.DateField(blank=True, default=datetime.date(2000, 1, 1))),
                ('foster_date', models.DateField(blank=True, default=datetime.date(2000, 1, 1))),
                ('litter_group', models.CharField(blank=True, default='', max_length=20)),
                ('update_dt', models.DateTimeField(blank=True, default=datetime.datetime(2000, 1, 1, 0, 0))),
            ],
            options={
                'ordering': ('name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='LitterObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=20)),
                ('litter_id', models.CharField(blank=True, default='', max_length=20)),
                ('any_available', models.BooleanField(default=False)),
                ('dogs', models.ManyToManyField(blank=True, to='wishlist.dogobject')),
            ],
        ),
        migrations.DeleteModel(
            name='DogProfile',
        ),
    ]
