# Generated by Django 4.1 on 2022-08-06 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0007_dog_appt_only'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dog',
            old_name='shelterluv_id',
            new_name='internal_id',
        ),
    ]
