# Generated by Django 4.1 on 2023-01-07 21:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0008_dogobject_litterobject_delete_dogprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='litterobject',
            name='latest_update',
            field=models.DateField(blank=True, default=datetime.date(2000, 1, 1)),
        ),
    ]
