# Generated by Django 4.1 on 2022-08-06 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0008_rename_shelterluv_id_dog_internal_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dog',
            old_name='internal_id',
            new_name='shelterluv_id',
        ),
    ]
