# Generated by Django 4.0 on 2022-08-14 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0009_rename_internal_id_dog_shelterluv_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dog',
            old_name='foster_date',
            new_name='return_foster_date',
        ),
        migrations.RenameField(
            model_name='dog',
            old_name='host_date',
            new_name='return_host_date',
        ),
    ]
