# Generated by Django 4.0 on 2022-08-07 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0009_rename_internal_id_dog_shelterluv_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='foster_date',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='host_date',
        ),
    ]
