# Generated by Django 4.1 on 2023-01-12 23:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0009_litterobject_latest_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='litterobject',
            name='return_date',
            field=models.DateField(blank=True, default=datetime.date(2000, 1, 1)),
        ),
    ]
