# Generated by Django 4.0 on 2022-08-14 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0010_rename_foster_date_dog_return_foster_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='return_foster_date',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='return_host_date',
        ),
        migrations.AddField(
            model_name='dog',
            name='foster_date',
            field=models.DateField(blank=True, default=datetime.date(2000, 1, 1)),
        ),
        migrations.AddField(
            model_name='dog',
            name='host_date',
            field=models.DateField(blank=True, default=datetime.date(2000, 1, 1)),
        ),
    ]
