# Generated by Django 4.1 on 2023-01-29 07:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0010_litterobject_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogobject',
            name='alter_date',
            field=models.DateField(blank=True, default=datetime.date(2000, 1, 1)),
        ),
    ]
