# Generated by Django 4.1 on 2023-01-30 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0011_dogobject_alter_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='litterobject',
            name='any_available',
            field=models.BooleanField(default=True),
        ),
    ]
