# Generated by Django 4.1 on 2022-08-20 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0010_remove_dog_foster_date_remove_dog_host_date'),
        ('wishlist', '0011_remove_dog_return_foster_date_and_more'),
    ]

    operations = [
    ]
