# Generated by Django 4.1 on 2022-08-20 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0012_merge_20220820_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='foster_date',
            field=models.DateField(blank=True, default=datetime.date(2000, 1, 1)),
        ),
        migrations.AddField(
            model_name='dog',
            name='host_date',
            field=models.DateField(blank=True, default=datetime.date(2000, 1, 1)),
        ),
    ]
