# Generated by Django 4.0 on 2021-12-26 02:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('6', 'Sunday'), ('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday')], default='0', max_length=1)),
                ('time', models.TimeField(default=datetime.time(12, 0))),
                ('appt_type', models.CharField(choices=[('1', 'Adults'), ('2', 'Puppies'), ('3', 'Puppies or Adults'), ('4', 'Surrender'), ('5', 'Adoption'), ('6', 'FTA')], default='1', max_length=1)),
            ],
            options={
                'ordering': ('time', 'appt_type'),
            },
        ),
        migrations.CreateModel(
            name='TimeslotTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('6', 'Sunday'), ('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday')], default='0', max_length=1)),
                ('time', models.TimeField(default=datetime.time(12, 0))),
                ('appointments', models.ManyToManyField(blank=True, to='schedule_template.AppointmentTemplate')),
            ],
            options={
                'ordering': ('time',),
            },
        ),
        migrations.CreateModel(
            name='Daily_Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('6', 'Sunday'), ('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday')], default='0', max_length=1)),
                ('timeslots', models.ManyToManyField(blank=True, to='schedule_template.TimeslotTemplate')),
            ],
        ),
    ]
