# Generated by Django 4.0 on 2022-03-22 00:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_template', '0003_remove_daily_schedule_bah'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_adopter_upload', models.DateField(default=datetime.date(2022, 3, 21))),
            ],
        ),
    ]
