# Generated by Django 4.0 on 2022-07-19 00:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_template', '0027_alter_appointmenttemplate_appt_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='last_adopter_upload',
            field=models.DateField(default=datetime.date(2022, 7, 18)),
        ),
    ]
