# Generated by Django 4.1 on 2023-02-11 05:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_template', '0052_alter_appointmenttemplate_appt_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='last_adopter_upload',
            field=models.DateField(default=datetime.date(2023, 2, 11)),
        ),
    ]
