# Generated by Django 4.0 on 2022-03-25 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(blank=True, default='', max_length=200)),
                ('text', models.TextField(blank=True, default='')),
            ],
        ),
    ]
