# Generated by Django 4.0 on 2022-03-25 23:20

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('email_mgr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
