# Generated by Django 4.0 on 2022-03-26 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_mgr', '0002_alter_emailtemplate_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='text',
            field=models.TextField(),
        ),
    ]
