# Generated by Django 4.0 on 2022-03-26 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_mgr', '0003_alter_emailtemplate_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(blank=True, default='', max_length=200)),
                ('text', models.TextField()),
            ],
        ),
    ]
