# Generated by Django 4.0 on 2022-03-26 01:30

import ckeditor.fields
from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('email_mgr', '0004_emailtemplate2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailtemplate2',
            name='text',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
