# Generated by Django 4.0 on 2022-03-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_mgr', '0006_alter_emailtemplate_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='plain',
            field=models.TextField(blank=True, null=True),
        ),
    ]
