# Generated by Django 4.0 on 2022-03-27 21:13

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('email_mgr', '0008_alter_emailtemplate_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'ordering': ('template_name',)},
        ),
        migrations.AlterField(
            model_name='emailtemplate2',
            name='text',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
