# Generated by Django 4.0 on 2022-05-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_mgr', '0011_pendingmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
