# Generated by Django 4.0 on 2022-05-26 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_mgr', '0013_emailtemplate_active_emailtemplate_file1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='file1',
            field=models.FileField(blank=True, default=None, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='file2',
            field=models.FileField(blank=True, default=None, null=True, upload_to='uploads/'),
        ),
    ]
