# Generated by Django 2.0.2 on 2021-12-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appt_calendar', '0002_auto_20211203_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='adopter_choice',
            field=models.CharField(choices=[('1', 'Sam Leifer'), ('2', 'Sam Leifer')], default='1', max_length=1),
        ),
    ]
