# Generated by Django 2.0.2 on 2021-12-03 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appt_calendar', '0004_auto_20211203_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='adopter_choice',
        ),
    ]
