# Generated by Django 2.0.2 on 2021-12-05 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appt_calendar', '0007_auto_20211205_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
