# Generated by Django 2.0.2 on 2021-12-11 19:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appt_calendar', '0012_auto_20211210_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='outcome',
            field=models.CharField(choices=[('1', 'Adoption'), ('2', 'Chosen'), ('3', 'FTA'), ('4', 'No Decision')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=datetime.date(2021, 12, 11)),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='date',
            field=models.DateField(default=datetime.date(2021, 12, 11)),
        ),
    ]
