# Generated by Django 2.0.2 on 2021-12-17 00:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appt_calendar', '0014_auto_20211212_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=datetime.date(2021, 12, 17)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='outcome',
            field=models.CharField(choices=[('1', 'NA'), ('2', 'Adoption'), ('3', 'Chosen'), ('4', 'FTA'), ('5', 'No Decision'), ('6', 'Ready To Roll'), ('7', 'Paperwork Scheduled')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='date',
            field=models.DateField(default=datetime.date(2021, 12, 17)),
        ),
    ]
