# Generated by Django 2.0.2 on 2021-12-17 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appt_calendar', '0015_auto_20211217_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='bringing_dog',
            field=models.BooleanField(default=False),
        ),
    ]
