# Generated by Django 4.0 on 2021-12-26 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appt_calendar', '0019_alter_appointment_date_alter_appointment_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ('time', 'appt_type', 'id')},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appt_type',
            field=models.CharField(choices=[('1', 'Adults'), ('2', 'Puppies'), ('3', 'Puppies or Adults'), ('4', 'Surrender'), ('5', 'Adoption Paperwork'), ('6', 'FTA Paperwork'), ('7', 'Visit')], default='1', max_length=1),
        ),
    ]
