# Generated by Django 4.0 on 2021-12-29 21:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appt_calendar', '0019_alter_appointment_date_alter_appointment_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ('time', 'appt_type', 'id')},
        ),
        migrations.AddField(
            model_name='appointment',
            name='comm_adopted_dogs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='comm_limited_hypo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='comm_limited_other',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='comm_limited_puppies',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='comm_limited_small',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appt_type',
            field=models.CharField(choices=[('1', 'Adults'), ('2', 'Puppies'), ('3', 'Puppies or Adults'), ('4', 'Surrender'), ('5', 'Adoption Paperwork'), ('6', 'FTA Paperwork'), ('7', 'Visit')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=datetime.date(2021, 12, 29)),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='date',
            field=models.DateField(default=datetime.date(2021, 12, 29)),
        ),
    ]
