# Generated by Django 4.0 on 2022-02-21 05:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('appt_calendar', '0023_alter_appointment_date_alter_timeslot_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 2, 21, 5, 9, 57, 98597, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 2, 21, 5, 9, 57, 100715, tzinfo=utc)),
        ),
    ]
