# Generated by Django 4.0 on 2022-04-28 23:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('appt_calendar', '0065_dailyannouncement_alter_appointment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 4, 28, 23, 12, 37, 654367, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='last_update_sent',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 4, 28, 23, 12, 37, 655364, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='outcome',
            field=models.CharField(choices=[('1', 'NA'), ('2', 'Adoption'), ('3', 'Chosen'), ('4', 'FTA'), ('5', 'No Decision'), ('6', 'No Show'), ('7', 'Ready To Roll'), ('8', 'Paperwork Scheduled'), ('9', 'Chosen - needs vetting'), ('10', 'Chosen - needs well check')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='dailyannouncement',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 4, 28, 23, 12, 37, 653370, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 4, 28, 23, 12, 37, 656361, tzinfo=utc)),
        ),
    ]
