# Generated by Django 4.0 on 2022-05-26 05:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('appt_calendar', '0087_alter_appointment_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2022, 5, 26, 5, 8, 13, 436980, tzinfo=utc))),
                ('text', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ('time', 'adopter', 'appt_type', 'id')},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 26, 5, 8, 13, 437978, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='last_update_sent',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 5, 26, 5, 8, 13, 438975, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='dailyannouncement',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 26, 5, 8, 13, 435983, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 26, 5, 8, 13, 439972, tzinfo=utc)),
        ),
    ]
