# Generated by Django 4.0 on 2022-06-11 00:57

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('adopter', '0043_adopter_age_preference_adopter_gender_preference_and_more'),
        ('appt_calendar', '0088_internalannouncement_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='adopter',
            field=models.ForeignKey(blank=True, limit_choices_to={'has_current_appt': False, 'status': '1'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adopter.adopter'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='adopter_notes',
            field=models.TextField(blank=True, default='', max_length='100'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 6, 11, 0, 57, 16, 267275, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='last_update_sent',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 6, 11, 0, 57, 16, 267275, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='outcome',
            field=models.CharField(choices=[('1', 'NA'), ('2', 'Adoption'), ('3', 'Chosen'), ('4', 'FTA'), ('5', 'No Decision'), ('6', 'No Show'), ('7', 'Ready To Roll'), ('8', 'Paperwork Scheduled'), ('9', 'Chosen - needs vetting'), ('10', 'Chosen - needs well check'), ('11', 'Error')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='dailyannouncement',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 6, 11, 0, 57, 16, 266249, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='internalannouncement',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 6, 11, 0, 57, 16, 266249, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 6, 11, 0, 57, 16, 267275, tzinfo=utc)),
        ),
    ]
