# Generated by Django 4.0 on 2022-06-11 02:02

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('adopter', '0043_adopter_age_preference_adopter_gender_preference_and_more'),
        ('appt_calendar', '0089_alter_appointment_adopter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='adopter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adopter.adopter'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 6, 11, 2, 2, 41, 69314, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='last_update_sent',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 6, 11, 2, 2, 41, 69314, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='dailyannouncement',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 6, 11, 2, 2, 41, 67318, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='internalannouncement',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 6, 11, 2, 2, 41, 68315, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 6, 11, 2, 2, 41, 70309, tzinfo=utc)),
        ),
    ]
