# Generated by Django 4.0 on 2022-07-01 23:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('appt_calendar', '0091_alter_appointment_adopter_alter_appointment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='late_notice',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appt_type',
            field=models.CharField(choices=[('1', 'Adults'), ('2', 'Puppies'), ('3', 'Puppies and/or Adults'), ('4', 'Surrender'), ('5', 'Adoption Paperwork'), ('6', 'FTA Paperwork'), ('7', 'Visit')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 7, 1, 23, 6, 24, 991907, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='last_update_sent',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 7, 1, 23, 6, 24, 991907, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='dailyannouncement',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 7, 1, 23, 6, 24, 990909, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='internalannouncement',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 7, 1, 23, 6, 24, 990909, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 7, 1, 23, 6, 24, 992903, tzinfo=utc)),
        ),
    ]
