# Generated by Django 4.0 on 2022-07-02 00:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('appt_calendar', '0093_appointment_rtr_notif_date_alter_appointment_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='late_notice',
            new_name='short_notice',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 7, 2, 0, 7, 22, 378053, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='last_update_sent',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 7, 2, 0, 7, 22, 378053, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='dailyannouncement',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 7, 2, 0, 7, 22, 377058, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='internalannouncement',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 7, 2, 0, 7, 22, 377058, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 7, 2, 0, 7, 22, 379018, tzinfo=utc)),
        ),
    ]
