# Generated by Django 4.0 on 2022-07-13 01:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('appt_calendar', '0098_shortnotice_backup_str_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortnotice',
            name='header_str',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='adopter_notes',
            field=models.TextField(blank=True, default='', max_length='50'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 7, 13, 1, 4, 0, 903350, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='last_update_sent',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 7, 13, 1, 4, 0, 903350, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='dailyannouncement',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 7, 13, 1, 4, 0, 902350, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='internalannouncement',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 7, 13, 1, 4, 0, 902350, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shortnotice',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 7, 13, 1, 4, 0, 905319, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 7, 13, 1, 4, 0, 904340, tzinfo=utc)),
        ),
    ]
