<<<<<<< HEAD
# Generated by Django 4.0 on 2022-08-07 17:38
=======
# Generated by Django 4.0 on 2022-08-14 16:25
>>>>>>> apptdogs

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('appt_calendar', '0110_alter_appointment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
<<<<<<< HEAD
            field=models.DateField(default=datetime.datetime(2022, 8, 7, 17, 38, 26, 979335, tzinfo=utc)),
=======
            field=models.DateField(default=datetime.datetime(2022, 8, 14, 16, 25, 40, 54163, tzinfo=utc)),
>>>>>>> apptdogs
        ),
        migrations.AlterField(
            model_name='appointment',
            name='last_update_sent',
<<<<<<< HEAD
            field=models.DateField(blank=True, default=datetime.datetime(2022, 8, 7, 17, 38, 26, 979335, tzinfo=utc)),
=======
            field=models.DateField(blank=True, default=datetime.datetime(2022, 8, 14, 16, 25, 40, 54163, tzinfo=utc)),
>>>>>>> apptdogs
        ),
        migrations.AlterField(
            model_name='dailyannouncement',
            name='date',
<<<<<<< HEAD
            field=models.DateField(default=datetime.datetime(2022, 8, 7, 17, 38, 26, 978340, tzinfo=utc)),
=======
            field=models.DateField(default=datetime.datetime(2022, 8, 14, 16, 25, 40, 53166, tzinfo=utc)),
>>>>>>> apptdogs
        ),
        migrations.AlterField(
            model_name='internalannouncement',
            name='date',
<<<<<<< HEAD
            field=models.DateField(default=datetime.datetime(2022, 8, 7, 17, 38, 26, 978340, tzinfo=utc)),
=======
            field=models.DateField(default=datetime.datetime(2022, 8, 14, 16, 25, 40, 53166, tzinfo=utc)),
>>>>>>> apptdogs
        ),
        migrations.AlterField(
            model_name='shortnotice',
            name='date',
<<<<<<< HEAD
            field=models.DateField(default=datetime.datetime(2022, 8, 7, 17, 38, 26, 980330, tzinfo=utc)),
=======
            field=models.DateField(default=datetime.datetime(2022, 8, 14, 16, 25, 40, 56158, tzinfo=utc)),
>>>>>>> apptdogs
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='date',
<<<<<<< HEAD
            field=models.DateField(default=datetime.datetime(2022, 8, 7, 17, 38, 26, 979335, tzinfo=utc)),
=======
            field=models.DateField(default=datetime.datetime(2022, 8, 14, 16, 25, 40, 54163, tzinfo=utc)),
>>>>>>> apptdogs
        ),
    ]
