# Generated by Django 4.0 on 2022-04-10 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dashboard', '0002_alter_adminprofile_signature'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminProfile',
            new_name='Profile',
        ),
    ]
