# Generated by Django 4.1 on 2022-11-21 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_profile_ac_show_adopter_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ac_show_cancel_adopter',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ac_show_enter_decision',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ac_show_print_application',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ac_show_reschedule_adopter',
        ),
    ]
