# Generated by Django 4.1 on 2022-11-24 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_profile_ac_show_cancel_adopter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ac_show_adopter_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='ac_show_adopter_phone',
            field=models.BooleanField(default=True),
        ),
    ]
