# Generated by Django 4.1 on 2022-11-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_profile_ac_show_adopter_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ac_show_adopter_description',
            field=models.BooleanField(default=True),
        ),
    ]
