# Generated by Django 4.1 on 2022-12-20 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_profile_ac_show_counselor'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ac_show_dog_in_extended_host_comm',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='ac_show_dog_in_medical_foster_comm',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='ac_show_dog_is_popular_comm',
            field=models.BooleanField(default=True),
        ),
    ]
