# Generated by Django 4.1 on 2022-12-22 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_profile_ac_show_dog_in_extended_host_comm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ac_show_dog_is_popular_low_chances_comm',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='ac_show_dog_not_here_yet_comm',
            field=models.BooleanField(default=True),
        ),
    ]
