# Generated by Django 4.1 on 2023-02-02 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_profile_ac_show_dog_is_popular_low_chances_comm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ac_show_watchlist',
            field=models.BooleanField(default=True),
        ),
    ]
