# Generated by Django 4.0 on 2022-04-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='', max_length=500)),
                ('answer', models.TextField(default='')),
                ('order', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ('order', 'question'),
            },
        ),
        migrations.CreateModel(
            name='FAQSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('order', models.IntegerField(default=1)),
                ('questions', models.ManyToManyField(blank=True, to='visit_and_faq.FAQ')),
            ],
            options={
                'ordering': ('order', 'name'),
            },
        ),
    ]
