# Generated by Django 4.0 on 2022-04-10 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visit_and_faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqsection',
            options={'ordering': ('id', 'order', 'name')},
        ),
    ]
