# Generated by Django 4.0 on 2022-04-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit_and_faq', '0003_visitorinstruction'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(default='', max_length=500)),
                ('text', models.TextField(default='')),
                ('order', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ('order', 'header'),
            },
        ),
        migrations.CreateModel(
            name='HelpSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('order', models.IntegerField(default=1)),
                ('topics', models.ManyToManyField(blank=True, to='visit_and_faq.FAQ')),
            ],
            options={
                'ordering': ('id', 'order', 'name'),
            },
        ),
    ]
