# Generated by Django 4.0 on 2022-04-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit_and_faq', '0004_helptopic_helpsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpsection',
            name='topics',
            field=models.ManyToManyField(blank=True, to='visit_and_faq.HelpTopic'),
        ),
    ]
