# Generated by Django 4.1 on 2023-01-10 04:43

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_volunteering', '0002_alter_corporatevolunteeringorganization_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corporatevolunteeringevent',
            name='org',
        ),
        migrations.AddField(
            model_name='corporatevolunteeringevent',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='corporatevolunteeringevent',
            name='event_counselor',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='corporatevolunteeringevent',
            name='event_end_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AddField(
            model_name='corporatevolunteeringevent',
            name='event_start_time',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
        migrations.AddField(
            model_name='corporatevolunteeringevent',
            name='event_task',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='corporatevolunteeringevent',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corporate_volunteering.corporatevolunteeringorganization'),
        ),
        migrations.AddField(
            model_name='corporatevolunteeringevent',
            name='volunteer_maximum',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='corporatevolunteeringevent',
            name='volunteer_minimum',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='corporatevolunteeringorganization',
            name='auth_code',
            field=models.IntegerField(default=100000, validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(999999)]),
        ),
        migrations.AddField(
            model_name='corporatevolunteeringorganization',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
