# Generated by Django 4.1 on 2023-01-10 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_volunteering', '0004_rename_corporatevolunteeringorganization_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='has_event',
            field=models.BooleanField(default=False),
        ),
    ]
