# Generated by Django 4.1 on 2023-01-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_volunteering', '0005_organization_has_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteeringevent',
            name='donation_received',
            field=models.BooleanField(default=False),
        ),
    ]
