# Generated by Django 4.1 on 2023-01-10 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_volunteering', '0006_volunteeringevent_donation_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteeringevent',
            name='volunteer_confirmed_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
