# Generated by Django 4.1 on 2023-01-17 05:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_volunteering', '0008_alter_organization_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteeringevent',
            name='event_start_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
