# Generated by Django 4.1 on 2023-01-19 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_volunteering', '0009_alter_volunteeringevent_event_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteeringevent',
            name='marked_as_complete',
            field=models.BooleanField(default=False),
        ),
    ]
