# Generated by Django 4.1 on 2023-01-19 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_volunteering', '0010_volunteeringevent_marked_as_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='donation_interest',
        ),
        migrations.RemoveField(
            model_name='volunteeringevent',
            name='volunteer_confirmed_count',
        ),
    ]
