# Generated by Django 4.1 on 2023-01-29 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_volunteering', '0011_remove_organization_donation_interest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteeringevent',
            name='posted_social_media',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteeringevent',
            name='sent_thank_you',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteeringevent',
            name='waivers_complete',
            field=models.BooleanField(default=False),
        ),
    ]
