# Generated by Django 4.1 on 2023-01-30 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_volunteering', '0012_volunteeringevent_posted_social_media_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteeringevent',
            old_name='volunteer_maximum',
            new_name='headcount',
        ),
        migrations.RemoveField(
            model_name='volunteeringevent',
            name='volunteer_minimum',
        ),
        migrations.AddField(
            model_name='volunteeringevent',
            name='activity_level',
            field=models.CharField(choices=[('0', 'Unknown'), ('1', 'Light'), ('2', 'Moderate'), ('3', 'Heavy')], default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='volunteeringevent',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
