# Generated by Django 2.0.2 on 2021-12-02 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adopter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adopter_first_name', models.CharField(blank=True, default='', max_length=200)),
                ('adopter_last_name', models.CharField(blank=True, default='', max_length=200)),
                ('adopter_email', models.EmailField(blank=True, default='', max_length=254)),
            ],
            options={
                'ordering': ('adopter_last_name',),
            },
        ),
    ]
