# Generated by Django 2.0.2 on 2021-12-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopter',
            name='acknowledged_faq',
            field=models.BooleanField(default=False),
        ),
    ]
