# Generated by Django 2.0.2 on 2021-12-09 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopter', '0002_adopter_acknowledged_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopter',
            name='lives_with_parents',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adopter',
            name='out_of_state',
            field=models.BooleanField(default=False),
        ),
    ]
