# Generated by Django 2.0.2 on 2021-12-09 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopter', '0003_auto_20211209_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopter',
            name='adopting_foster',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adopter',
            name='adopting_host',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adopter',
            name='friend_of_foster',
            field=models.BooleanField(default=False),
        ),
    ]
