# Generated by Django 2.0.2 on 2021-12-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopter', '0005_adopter_chosen_dog'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopter',
            name='has_current_appt',
            field=models.BooleanField(default=False),
        ),
    ]
