# Generated by Django 2.0.2 on 2021-12-17 00:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopter', '0006_adopter_has_current_appt'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopter',
            name='alert_date',
            field=models.DateField(blank=True, default=datetime.date(2000, 1, 1)),
        ),
    ]
