# Generated by Django 4.0 on 2021-12-26 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopter', '0007_adopter_alert_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopter',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
