# Generated by Django 4.0 on 2021-12-30 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopter', '0009_alter_adopter_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopter',
            name='visits_to_date',
            field=models.IntegerField(default=0),
        ),
    ]
