# Generated by Django 4.0 on 2022-02-21 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopter', '0010_adopter_visits_to_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopter',
            name='app_interest',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
