# Generated by Django 4.0 on 2022-03-10 05:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopter', '0011_adopter_app_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopter',
            name='accept_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 3, 9)),
        ),
    ]
