# Generated by Django 4.0 on 2022-03-11 04:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopter', '0012_adopter_accept_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopter',
            name='status',
            field=models.CharField(choices=[('1', 'Approved'), ('2', 'Blocked')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='adopter',
            name='accept_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 3, 10)),
        ),
    ]
