# Generated by Django 4.0 on 2022-03-22 00:37

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopter', '0014_adopter_auth_code_alter_adopter_accept_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopter',
            name='accept_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 3, 21)),
        ),
        migrations.AlterField(
            model_name='adopter',
            name='auth_code',
            field=models.IntegerField(default=100000, validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(999999)]),
        ),
    ]
