# Generated by Django 4.0 on 2022-04-09 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopter', '0025_faqsection_alter_adopter_accept_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='', max_length=500)),
                ('answer', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='faqsection',
            name='questions',
            field=models.ManyToManyField(blank=True, to='adopter.FAQ'),
        ),
    ]
