# Generated by Django 4.0 on 2022-04-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopter', '0026_faq_faqsection_questions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ('order', 'question')},
        ),
        migrations.AlterModelOptions(
            name='faqsection',
            options={'ordering': ('order', 'name')},
        ),
        migrations.AddField(
            model_name='faq',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='faqsection',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
