# Generated by Django 4.0 on 2022-04-09 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopter', '0027_alter_faq_options_alter_faqsection_options_faq_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faqsection',
            name='questions',
        ),
        migrations.DeleteModel(
            name='FAQ',
        ),
        migrations.DeleteModel(
            name='FAQSection',
        ),
    ]
