# Generated by Django 4.0 on 2022-04-10 05:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopter', '0028_remove_faqsection_questions_delete_faq_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopter',
            name='accept_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 4, 10)),
        ),
    ]
