# Generated by Django 4.0 on 2022-04-30 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopter', '0035_adopter_application_id_alter_adopter_accept_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopter',
            name='city',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='adopter',
            name='state',
            field=models.CharField(default='', max_length=2),
        ),
    ]
