# Generated by Django 4.0 on 2022-05-07 21:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopter', '0037_adopter_activity_level_adopter_has_fence_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adopter',
            options={'ordering': ('f_name', 'l_name')},
        ),
        migrations.RenameField(
            model_name='adopter',
            old_name='adopter_first_name',
            new_name='f_name',
        ),
        migrations.RenameField(
            model_name='adopter',
            old_name='adopter_last_name',
            new_name='l_name',
        ),
        migrations.RenameField(
            model_name='adopter',
            old_name='adopter_email',
            new_name='primary_email',
        ),
        migrations.AlterField(
            model_name='adopter',
            name='accept_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 5, 7)),
        ),
    ]
