# Generated by Django 4.0 on 2022-05-08 05:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0003_dog_shelterluv_status'),
        ('adopter', '0038_alter_adopter_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopter',
            name='wishlist',
            field=models.ManyToManyField(null=True, to='wishlist.Dog'),
        ),
        migrations.AlterField(
            model_name='adopter',
            name='accept_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 5, 8)),
        ),
    ]
