# Generated by Django 4.0 on 2022-06-11 00:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0003_dog_shelterluv_status'),
        ('adopter', '0042_alter_adopter_accept_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopter',
            name='age_preference',
            field=models.CharField(choices=[('1', 'No Preference'), ('2', 'Puppies Only'), ('3', 'Adults Only')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='adopter',
            name='gender_preference',
            field=models.CharField(choices=[('1', 'No Preference'), ('2', 'Female Only'), ('3', 'Male Only')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='adopter',
            name='hypo_preferred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adopter',
            name='max_weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adopter',
            name='min_weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='adopter',
            name='accept_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 6, 10)),
        ),
        migrations.AlterField(
            model_name='adopter',
            name='activity_level',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='adopter',
            name='city',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='adopter',
            name='has_fence',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='adopter',
            name='housing',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='adopter',
            name='housing_type',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='adopter',
            name='state',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='adopter',
            name='wishlist',
            field=models.ManyToManyField(blank=True, null=True, to='wishlist.Dog'),
        ),
    ]
