# Generated by Django 4.1 on 2023-02-11 05:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopter', '0075_adopter_open_house_appt_alter_adopter_accept_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopter',
            name='open_house_signup_timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2000, 1, 1, 0, 0)),
        ),
        migrations.AlterField(
            model_name='adopter',
            name='alert_date',
            field=models.DateField(blank=True, default=datetime.date(2000, 1, 1)),
        ),
    ]
