# Generated by Django 4.1 on 2023-03-13 23:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopter', '0076_adopter_open_house_signup_timestamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdopterUploadSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_adopter_id_uploaded', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='adopter',
            name='accept_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 3, 13)),
        ),
    ]
